# .github/dependabot.yml

version: 2
updates:
  - package-ecosystem: "npm"           # Specifies npm as the package manager
    directory: "/"                     # Root directory where the package.json is located
    schedule:
      interval: "weekly"               # Checks for updates every week
    open-pull-requests-limit: 5        # Maximum number of open PRs at one time
    commit-message:
      prefix: "chore"                  # Prefixes commit messages with "chore"
    ignore:
      - dependency-name: "some-package" # Example to ignore specific dependencies
        versions: ["1.x", "2.0.0"]      # Ignore specific versions, if necessary
    # Allows separate security updates if vulnerabilities are detected
    allow:
      - dependency-type: "all"          # Monitors both dependencies and devDependencies
