import type { Metadata } from 'next';
import '../globals.css';
import Navbar from '@/components/common/navbar';
import Footer from '@/components/common/footer';
import CustomCursor from '@/components/ui/CustomCursor';
import { Providers } from '@/lib/providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Providers>
          <CustomCursor />
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
